### ISSUE TITLE
Using "English" in api docs example is not helpful

### ISSUE THREAD

**Issue by codersquid** [pyvideo/richard#295]
I got feedback from a conference organizer asking what language codes to use, and they pointed out that using "English" in the example is not a helpful example.

> As we have two talks in Euskara (Basque) I hope that is valid language to specify. For that and the 5 or so Spanish talks would I use Euskara/Español or Basque/Spanish? I probably can see what you do with other videos. Using "English" as the example language in your English documentation is not really useful to make that kind of distinction.

We can improve that section of the docs. We could have an example with a language other than English, and we could also give information on how to add new languages, and how the languages are stored.

And it seems we would do better to use an iso short code for specifying the language versus the description string.

**Comment by willkg** [comment]
richard was never built to host videos in multiple languages. The ui is entirely in English and thus everything is currently English-oriented. Originally, I was pushing to have people do separate instances for other languages since there's no way I could curate non-English videos. That's why https://pyvideo.ru/ exists.

Issue #182 covers changing that situation. That work should rethink everything language-wise.

**Comment by codersquid** [comment]
In that case, I'll ask them what language specification they'd prefer to use and the other issue would include updating docs along with everything else. Okay? I'll close this.

**Comment by willkg** [comment]
I didn't mean to suggest we should close this. I just thought the context/background would be helpful. Sorry about that!
